name: affbench
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2023.01.10
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.3
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.9.12
  - readline=8.1.2
  - setuptools=66.0.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.2.5
  - zlib=1.2.12
